# This workflow will do a clean install of node dependencies, build the source code and run test
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        make lint
        make utest
        make build 
        make lambda
      working-directory: authClientCredentials
    - run: |
        make lint
        make utest
        make build 
        make lambda
      working-directory: authXealth

